FROM node:20

WORKDIR /app

# نسخ package.json و package-lock.json من مجلد server
COPY server/package*.json ./

# تثبيت الاعتمادات
RUN npm install

# نسخ باقي كود السيرفر
COPY server .

EXPOSE 5000

CMD ["npm","start"]