# Use Node.js 20
FROM node:20

# Set working directory
WORKDIR /app

# Copy only package.json and package-lock.json from the client folder
COPY client/package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the client code
COPY client .

# Build Next.js for production
RUN npm run build

# Expose port 3000
EXPOSE 3000

# Start Next.js
CMD ["npm","start"]